export enum QueryKey {
  // User info
  GET_ME = "GET_ME",

  // User settings
  GET_USER_SETTINGS = "GET_USER_SETTINGS",

  // Departments
  GET_DEPARTMENT = "GET_DEPARTMENT",
  GET_DEPARTMENTS = "GET_DEPARTMENTS",

  // Employees
  GET_EMPLOYEES = "GET_EMPLOYEES",
  GET_EMPLOYEES_BY_DEPARTMENT_ID = "GET_EMPLOYEES_BY_DEPARTMENT_ID",

  // System Settings
  GET_SYSTEM_SETTINGS = "GET_SYSTEM_SETTINGS",

  // Files
  GET_FILE = "GET_FILE",
  GET_FILES = "GET_FILES",
}
