// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/smart-hmm/smart-hmm/internal/config"
)

// Injectors from wire.go:

func Build(ctx context.Context, cfg *config.Config) (*Container, error) {
	infrastructures, err := buildInfrastructures(ctx, cfg)
	if err != nil {
		return nil, err
	}
	pool := provideDBPool(infrastructures)
	repositories := buildRepositories(pool)
	usecases := buildUsecases(repositories, infrastructures)
	handlers := buildHandlers(usecases, repositories)
	mux := buildRouter(handlers, infrastructures)
	container := buildContainer(cfg, infrastructures, repositories, usecases, handlers, mux)
	return container, nil
}
