import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeToggle } from "../components/ui/theme-toggle";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/components/providers/store-provider";
import ReactQueryProvider from "@/components/providers/query-provider";
import AuthProvider from "@/components/providers/auth-provider";
import "./globals.css";
import RBACProvider from "@/components/providers/rbac-provider";
import { Suspense, useContext } from "react";
import Loading from "./loading";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <ReactQueryProvider>
          <StoreProvider>
            <AuthProvider>
              <RBACProvider>
                <div className="fixed top-2 right-2 z-4">
                  <ThemeToggle />
                </div>
                <Suspense fallback={<Loading />}>{children}</Suspense>
                <ToastContainer />
              </RBACProvider>
            </AuthProvider>
          </StoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
