import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeToggle } from "../components/ui/theme-toggle";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/components/providers/store-provider";
import ReactQueryProvider from "@/components/providers/query-provider";
import AuthProvider from "@/components/providers/auth-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='light'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProvider>
          <StoreProvider>
            <AuthProvider>
              <div className="fixed top-2 right-2"><ThemeToggle /></div>
              {children}
              <ToastContainer />
            </AuthProvider>
          </StoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
